package commands.enums;

public enum CommandType {

    CREATEMEMBER,
    SHOWALLMEMBERS,
    SHOWMEMBERACTIVITY,
    CREATETEAM,
    SHOWTEAMS,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    SHOWTEAMMEMBERS,
    CREATEBOARDINTEAM,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CREATETASKINBOARD,
    CHANGEBUGDETAILS,
    CHANGESTORYDETAILS,
    CHANGEFEEDBACKDETAILS,
    ASSIGNTASK,
    UNAASIGNTASK,
    ADDTASKCOMMENT;

}
